### ISSUE TITLE
File could not found

### ISSUE THREAD

**Issue by eniserkaya** [eiceblue/Spire.Doc-for-Java#2]
I am trying to open existing file from Java code. 
Spire can not find file given path.

com.spire.doc.packages.sprlzt: Could not find file "/path-of-file/src/main/resources/files/myFile.docx".
	at com.spire.doc.packages.spryxt.sprâ–“â€“(FileInfo.java:66)
	at com.spire.doc.Document.sprâˆ¯â”‡ï»¿â€”(Unknown Source)
	at com.spire.doc.Document.loadFromFile(Unknown Source)
	at com.spire.doc.Document.<init>(Unknown Source)

**Comment by eiceblue** [comment]
Hello, eniserkaya.
Thank you for your message. Based on the information you provided, I suspect that the issue might be caused by insufficient permissions to read the file. I suggest you place the file in the same directory as the program and try again.
Additionally, the current latest version of Spire.Doc for Java is 13.3.0. This new version includes more bug - fixes. If you still encounter problems after placing the file in the same directory, we recommend that you try using the new version.
If the problem persists, please send your file to support@e - [iceblue.com](https://iceblue.com/). We will respond to your query promptly.
our website：https://www.e-iceblue.com/Download/doc-for-java.html
