### ISSUE TITLE
Linux中生成文档时产生报错：找不到字体文件

### ISSUE THREAD

**Issue by lizhe-0423** [eiceblue/Spire.Doc-for-Java#4]
【版本】
最新版本：12.11.0
【原因】
在linux中生成文档时产生报错 找不到字体文件
java.lang.IllegalStateException: Cannot find any fonts in specified font sources.
【尝试解决方案】
linux上下载了对应文件
 1、设置字体路径
  document.setCustomFontsFolders("/usr/share/fonts/chinese/Fonts/");
2、设置字体
 tx.getCharacterFormat().setFontName("simsun");
simsun 就是在相应的/usr/share/fonts/chinese/Fonts/ 路径下 存在 simsun.ttl 文件
【最终解决】
无效、失败 java.lang.IllegalStateException: Cannot find any fonts in specified font sources.

【堆栈信息】

2024-11-18 11:42:22.012  INFO 1 --- [   async-task-1] c.j.t.o.template.manager.PreviewManager    43 : 字体路径设置成功路径为/usr/share/fonts/chinese/Fonts/
2024-11-18 11:42:22.018  INFO 1 --- [   async-task-1] c.j.t.o.template.manager.PreviewManager   170 : 表格行数：14
2024-11-18 11:42:22.020  INFO 1 --- [   async-task-1] c.j.t.o.template.manager.PreviewManager   210 : 填充表格行，表结构数量: 14
2024-11-18 11:42:22.237 ERROR 1 --- [  XNIO-1 task-1] c.j.t.c.l.e.BladeRestExceptionTranslator   83 : 服务器异常

java.util.concurrent.CompletionException: java.lang.IllegalStateException: Cannot find any fonts in specified font sources.
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
        at com.joysuch.tiji.core.context.BladeRunnableWrapper.run(BladeRunnableWrapper.java:54)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Cannot find any fonts in specified font sources.
        at com.spire.doc.packages.sprkvda.spr┩©(DocumentFontProvider.java:121)
        at com.spire.doc.packages.sprkvda.spr‣└—(DocumentFontProvider.java:44)
        at com.spire.doc.packages.sprkvda.spr╹¬(DocumentFontProvider.java:32)
        at com.spire.doc.packages.sprkvda.spr┉©(DocumentFontProvider.java:27)
        at com.spire.doc.packages.sprbzz.spr┨〠(Unknown Source)
        at com.spire.doc.packages.sprbzz.spr┦“—(Unknown Source)
        at com.spire.doc.packages.sprbzz.spr▊“—(Unknown Source)
        at com.spire.doc.packages.sprooz.spr╹‘—(Unknown Source)
        at com.spire.doc.packages.sprooz.spr┩‘—(Unknown Source)
        at com.spire.doc.packages.sprooz.spr∮‘—(Unknown Source)
        at com.spire.doc.packages.sprooz.spr╖’—(Unknown Source)
        at com.spire.doc.packages.sprooz.spr╄“—(Unknown Source)
        at com.spire.doc.packages.sprooz.spr┚“—(Unknown Source)
        at com.spire.doc.Table.spr⌦≂—(Unknown Source)
        at com.spire.doc.Table.spr㈭⃟≂—(Unknown Source)
        at com.spire.doc.packages.spryhy.spr▐℉(Unknown Source)
        at com.spire.doc.packages.sprqfy.spr▐℉(Unknown Source)
        at com.spire.doc.Table.spr⅙⅔(Unknown Source)
        at com.spire.doc.DocumentObject.spr┻⅕(Unknown Source)
        at com.spire.doc.Table.spr■⅔(Unknown Source)
        at com.spire.doc.DocumentObject.spr∫⅕(Unknown Source)
        at com.spire.doc.DocumentObject.spr┻⅕(Unknown Source)
        at com.spire.doc.Body.spr■⅔(Unknown Source)
        at com.spire.doc.DocumentObject.spr∫⅕(Unknown Source)
        at com.spire.doc.DocumentObject.spr┻⅕(Unknown Source)
        at com.spire.doc.Section.spr■⅔(Unknown Source)
        at com.spire.doc.DocumentObject.spr∫⅕(Unknown Source)
        at com.spire.doc.DocumentObject.spr┻⅕(Unknown Source)
        at com.spire.doc.Document.spr■⅔(Unknown Source)
        at com.spire.doc.packages.sprqfy.spr㈭⃟〠(Unknown Source)
        at com.spire.doc.packages.sprbtca.spr™⑶—(Unknown Source)
        at com.spire.doc.packages.sprbtca.spr‡⑶—(Unknown Source)
        at com.spire.doc.Document.spr┻…—(Unknown Source)
        at com.spire.doc.Document.saveToFile(Unknown Source)
        at com.joysuch.tiji.ones.template.manager.PreviewManager.saveDocument(PreviewManager.java:280)
        at com.joysuch.tiji.ones.template.manager.PreviewManager.generateDocument(PreviewManager.java:78)
        at com.joysuch.tiji.ones.template.service.impl.TemplateServiceImpl.lambda$preview$4(TemplateServiceImpl.java:290)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        ... 4 common frames omitted

**Comment by eiceblue** [comment]
您好，
感谢留言。根据您的描述判断，这个问题可能是权限不够因此无法读取到字体，建议您在和程序同级的目录建一个fonts文件夹，并将需要用到的字体放入其中，并赋予其权限。除此之外，您也可以选择参考这个帮助文档在linux机器安装字体：https://www.e-iceblue.cn/spiredocforjavaconversion/word-to-pdf-font-issue.html
如果还是有问题，欢迎发送邮件到support@e-iceblue.com，我们会及时回复您。
